### ISSUE TITLE
Socom 2 Not Connecting properly

### ISSUE THREAD

**Issue by Based-Skid** [FogNo23/DNASrep#3]
https://www.youtube.com/watch?v=gNsqjusU7q4&feature=youtu.be

Socom 3 and CA seem to validate properly

Socom 2 seems to have a connection failure.

socom 2 seems to only be making one request while socom 3 and ca make 2 requests.
- - [03/Oct/2017:19:19:16 -0400] "POST /us-gw/v2.5_i-connect HTTP/1.0" 200 328 "-" "open sesame asdfjkl"

**Comment by Based-Skid** [comment]
I should also note that i tested this with bobz1993's dnasrep implementation as well

**Comment by Blayer98** [comment]
Hey, how did you manage to set the server up? I've been having issues trying to set it up :/

**Comment by Based-Skid** [comment]
Well, This Dilemma Is Crazy.

Socom 2 R0001 (Base Game No MC Patch) Fails DNaSrep.

Socom 2 R0004  (MC Patch) Passes DNASrep

Socom 2 NTSC also Has 2 Greatest hits Versions On Top of Black Label.

BlackLabel,GreatestHits,and the Second Greatest hits Release All have Different SKU and Technically Different DNAS Authoring Data.

Working on This.
